import Papa from "papaparse";

const sampleRows = [
  {
    outletId: "CSV-001",
    tenDiemBan: "Hasaki Bến Nghé CSV",
    kenh: "MT",
    chuoi: "Hasaki",
    tinhThanh: "TP.HCM",
    quanHuyen: "Quận 1",
    phuongXa: "Bến Nghé",
    diaChi: "12 Đồng Khởi",
    cumNho: "Q1-A",
    salePhuTrach: "An Nguyễn",
    doanhSo3Thang: 285000000,
    soDon3Thang: 34,
    tiemNang: 5,
    ruiRoMatKhach: 4,
    toaDoX: 10.2,
    toaDoY: 10.8,
    ghiNhanF: "F4",
    ghiChu: "Khách trọng điểm",
  },
  {
    outletId: "CSV-002",
    tenDiemBan: "C2 Đa Kao CSV",
    kenh: "GT",
    chuoi: "C2 độc lập",
    tinhThanh: "TP.HCM",
    quanHuyen: "Quận 1",
    phuongXa: "Đa Kao",
    diaChi: "22 Nguyễn Đình Chiểu",
    cumNho: "Q1-B",
    salePhuTrach: "Bình Trần",
    doanhSo3Thang: 135000000,
    soDon3Thang: 18,
    tiemNang: 4,
    ruiRoMatKhach: 3,
    toaDoX: 14.5,
    toaDoY: 12.4,
    ghiNhanF: "F2",
    ghiChu: "Khách tăng trưởng",
  },
  {
    outletId: "CSV-003",
    tenDiemBan: "Guardian Võ Thị Sáu CSV",
    kenh: "MT",
    chuoi: "Guardian",
    tinhThanh: "TP.HCM",
    quanHuyen: "Quận 3",
    phuongXa: "Võ Thị Sáu",
    diaChi: "18 Võ Văn Tần",
    cumNho: "Q3-A",
    salePhuTrach: "Chi Lê",
    doanhSo3Thang: 90000000,
    soDon3Thang: 11,
    tiemNang: 3,
    ruiRoMatKhach: 2,
    toaDoX: 18.8,
    toaDoY: 13.5,
    ghiNhanF: "F1",
    ghiChu: "Khách duy trì",
  },
  {
    outletId: "CSV-004",
    tenDiemBan: "Minimart An Lạc CSV",
    kenh: "GT",
    chuoi: "Minimart gia đình",
    tinhThanh: "TP.HCM",
    quanHuyen: "Bình Tân",
    phuongXa: "An Lạc",
    diaChi: "9 Kinh Dương Vương",
    cumNho: "BTA-A",
    salePhuTrach: "Dung Phạm",
    doanhSo3Thang: 26000000,
    soDon3Thang: 4,
    tiemNang: 2,
    ruiRoMatKhach: 1,
    toaDoX: 41.2,
    toaDoY: 19.4,
    ghiNhanF: "F0.5",
    ghiChu: "CS từ xa nếu hết capacity",
  },
];

export const sampleOutletsCsv = Papa.unparse(sampleRows);

export const sampleExecutionHistoryCsv = Papa.unparse([
  {
    visitId: "2026-5-W1-OUT-011",
    month: 5,
    year: 2026,
    week: "W1",
    outletId: "OUT-011",
    salePhuTrach: "Chi Lê",
    actualStatus: "Dời lịch",
    actualVisitDate: "",
    actualRevenue: "",
    note: "Khách đổi lịch, cần bù tháng sau",
    carryToNextMonth: "true",
  },
  {
    visitId: "2026-5-W1-OUT-071",
    month: 5,
    year: 2026,
    week: "W1",
    outletId: "OUT-071",
    salePhuTrach: "Chi Lê",
    actualStatus: "Có đơn",
    actualVisitDate: "2026-05-05",
    actualRevenue: 12500000,
    note: "Đơn bổ sung trưng bày",
    carryToNextMonth: "false",
  },
  {
    visitId: "2026-5-W2-OUT-002",
    month: 5,
    year: 2026,
    week: "W2",
    outletId: "OUT-002",
    salePhuTrach: "Bình Trần",
    actualStatus: "Không gặp khách",
    actualVisitDate: "",
    actualRevenue: "",
    note: "Chủ vắng, ưu tiên bù",
    carryToNextMonth: "true",
  },
]);
